config/routes.rb
CountdownYammer::Application.routes.draw do

  get "/about", :to => 'welcome#about'
  resources :events do
    get '/advent_calendar(/:year(/:month))' => 'advent_calendar#index', :as => :advent_calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}    
  end

  root 'welcome#index'

  get 'sessions/create'

  get '/auth/yammer/callback', :to => 'sessions#create'
  get "sessions/destroy"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_event_calendar
end

app/models/event.rb
require 'yammer'

class Event < ActiveRecord::Base
  has_event_calendar
  
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  validates :name, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

  def self.post_to_yammer
    self.all.order(:created_at).each do |event|
      client = Yammer::Client.new(:access_token  => event.owner.token)
      days = (event.start_at - Time.now.utc.beginning_of_day).to_i / (60 * 60 * 24)
      client.create_message("#{event.name}まであと#{days}日！")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :my_events, class_name: 'Event', foreign_key: :owner_id
end

app/controllers/advent_calendar_controller.rb
class AdventCalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    event = Event.find(params[:event_id])

    @shown_month = Date.civil(@year, @month)

    strip_start, strip_end = Entry.get_start_and_end_dates(@shown_month)

    @event_strips = Entry.create_event_strips(strip_start, strip_end, [event])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize

  helper_method :current_user

  private
    def current_user
      @current_user ||= User.where(id:session[:user_id]).first if session[:user_id]
    end

    def authorize
      unless current_user
        redirect_to root_path, notice: "Please log in"
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :validate_owner, only:[:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.owner = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render action: 'index', status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render action: 'index', status: :created }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_at, :end_at)
    end

    def validate_owner
      redirect_to root_path, :status => 404 unless @event.owner == current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authorize, :only => [:create]

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_by(email:auth['info']['email'])
    user.name = auth['info']['nickname']
    user.token = auth[:credentials][:token]
    user.save
    session[:user_id] = user.id
    redirect_to events_path, :notice => "Hello #{user.name}."
  end

  def destroy
    reset_session
    redirect_to root_path, :notice => "You successfully logged out."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authorize
  def index
  end

  def about
  end
end

app/helpers/advent_calendar_helper.rb
module AdventCalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advent_calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/events/_form.html.erb
<div class="well">
  <fieldset>
    <legend>Event</legend>
    <%= form_for(@event, class: "form-horizontal") do |f| %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, class: 'control-label' %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :start_at %><br>
        <%= f.date_select :start_at %>
      </div>
      <div class="form-group">
        <%= f.label :end_at %><br>
        <%= f.date_select :end_at %>
      </div>
      <div class="actions">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </fieldset>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/index.html.erb
<h1>Everyone's Events</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped table-hover " >
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Owner</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.start_at.strftime('%Y/%m/%d') %></td>
            <td><%= event.end_at.strftime('%Y/%m/%d') %></td>
            <td><%= event.owner.name %></td>
            <td>
              <% if event.owner == current_user %>
                  <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-warning'%>
              <% end %>
            </td>
            <td>
              <% if event.owner == current_user %>
                  <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>



<%= link_to 'New Event', new_event_path, class: "glyphicon glyphicon-plus btn btn-primary" %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @event.start_at %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @event.end_at %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="well alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Countdown to Hawaii', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li>  <% if current_user  %></li>
<li>  <%= link_to "Everyone's Events", events_path %></li>
<li>  <%= link_to 'Sign out', '/sessions/destroy' %></li>
<li>  <% else%></li>
<li>  <%= link_to 'Sign in with Yammer', '/auth/yammer' %></li>
<li>  <% end %></li>
<li>  <%= link_to 'About', '/about' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Countdown to Hawaii" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Countdown to Hawaii" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="maximage">
      <%= image_tag('top.jpg', alt: "", width: 1024, height: 678) %>
    </div>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer >
    <small>Photo by <a href="http://www.flickr.com/people/ornellas/">Justin Ornellas</a> / <a href="http://creativecommons.org/licenses/by/2.0/">CC BY</a></small></footer>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>About</h1>
<p>This is a simple bot to make an atmosphere for exciting events like Hawaii trip, release of awesome products or a party in honor of the 20th anniversary of your company.</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h1>Countdown to Hawaii</h1>
<p>This is a simple bot to make an atmosphere for exciting events like Hawaii trip, release of awesome products or a party in honor of the 20th anniversary of your company.</p>

<% if current_user %>
  <p><%= link_to "Show everyone's events", events_path, class: "btn btn-primary btn-lg" %></p>
<% else %>
  <p><%= link_to 'Sign in with Yammer', '/auth/yammer', class: "btn btn-primary btn-lg" %></p>
<% end %>
</div>